[WIP]Dropbox/reports
Horizontal-org/Tella-iOS pull request #189
Opened 2024-09-17 20:30 UTC by ValbuenaG

For more information on contributing to Tella source code, see the [Contributor Guidelines](contributing/contributor_guide.md).

## Type of change

**Description:**

**Select the type of change(s) made in this pull request:**
- [ ] Bug fix *(Fixes an issue)*
- [ ] New feature *(Adds functionality)*
- [ ] Documentation *(Fix to documentation)*

----------------------------------------------------------------------------------------

Fixes #issue-number

## Proposed changes 

*
*
*

2024-10-04 13:03 UTC, Rimktarii requested changes

2024-10-04 13:15 UTC, dhekra-rouatbi requested changes

2024-10-04 13:15 UTC, dhekra-rouatbi commented on Tella/Domain/Entity/Dropbox/DropboxReportFile.swift
> +    var offset: Int64?
Can we use bytesSent ?

2024-10-07 11:19 UTC, dhekra-rouatbi requested changes

2024-10-07 11:21 UTC, dhekra-rouatbi requested changes

2024-10-07 11:21 UTC, dhekra-rouatbi commented on Tella/Data/Networking/APICall/APIError.swift
> +            return DropboxErrorParser.customDropboxErrorMessage(error: error)
What do you think of using an `APIError`  extension that contains `customDropboxErrorMessage` function ?

2024-10-07 12:25 UTC, dhekra-rouatbi requested changes

2024-10-07 12:25 UTC, dhekra-rouatbi commented on Tella/Scenes/Dropbox/ViewModel/DropboxOutboxViewModel.swift
> +        _ = dropboxRepository.handleRedirectURL(url) { authResult in
maybe we need to handle success and failure ? like in `DropboxServerViewModel` class

    func handleURLRedirect(url: URL) {
        _ = dropboxRepository.handleRedirectURL(url) { [weak self] authResult in
            guard let self = self else { return }
            
            switch authResult {
            case .success:
                self.signInState = .loaded(true)
                self.addServer()
            case .error(_, let description):
                self.signInState = .error(description ?? "")
            default:
                break
            }
        }
    }

2024-10-07 12:29 UTC, dhekra-rouatbi requested changes

2024-10-07 12:29 UTC, dhekra-rouatbi commented on Tella/Domain/Entity/Report/ReportVaultFile.swift
> +    var offset: Int64?
maybe here we can use `bytesSent` instead of adding an other `offset` variable

2024-10-08 09:08 UTC, dhekra-rouatbi requested changes

2024-10-08 09:08 UTC, dhekra-rouatbi commented on Tella/Domain/Entity/Dropbox/DropboxReportFile.swift
> +         offset: Int64? = nil,
I think `offset` is unused, could you remove it

2024-10-08 09:08 UTC, dhekra-rouatbi commented on Tella/Data/Database/Common/DatabaseConstants.swift
> +    static let cOffset = "c_offset"
I think `cOffset ` is unused, could you remove it

2024-10-08 09:21 UTC, dhekra-rouatbi requested changes

2024-10-08 09:21 UTC, dhekra-rouatbi commented on Tella/Data/Networking/Repositories/Dropbox/DropboxErrorParser.swift
> +extension APIError {
maybe we don't need a `static` for  `customDropboxErrorMessage` function ?

2024-10-08 10:35 UTC, dhekra-rouatbi requested changes

2024-10-08 10:35 UTC, dhekra-rouatbi commented on Tella/Scenes/Dropbox/ViewModel/DropboxOutboxViewModel.swift
> +        if reportViewModel.folderId != nil {
I think it's better to move the upload handling to the `DropboxRepository` and handling the result in the view model. 
There is an example  in `NextcloudOutboxViewModel` : `performSubmission()` function

2024-10-09 16:14 UTC, dhekra-rouatbi requested changes

2024-10-09 16:14 UTC, dhekra-rouatbi commented on Tella/Data/Networking/Repositories/Dropbox/DropboxRepository.swift
> +                try await uploadFile(
In my opinion Sending all the files in parallel is better than the serial upload to follow Tella web and Nextcloud implementation

2024-10-09 16:20 UTC, dhekra-rouatbi requested changes

2024-10-09 16:20 UTC, dhekra-rouatbi commented on Tella/Data/Networking/Repositories/Dropbox/DropboxRepository.swift
> +        let folderPath = "/\(name)"
can we create an extension to add "/" as a prefix ?

there is an extension to add a "/" as a prefix 
```
    func slash() -> String {
        return self.hasSuffix("/") ? self : self + "/"
    }

```

2024-10-09 16:21 UTC, dhekra-rouatbi requested changes

2024-10-09 16:21 UTC, dhekra-rouatbi commented on Tella/Data/Networking/Repositories/Dropbox/DropboxRepository.swift
> +                    to: "/\(folderResponse.name)",
https://github.com/Horizontal-org/Tella-iOS/pull/189#discussion_r1793812638

2024-10-09 16:21 UTC, dhekra-rouatbi commented on Tella/Data/Networking/Repositories/Dropbox/DropboxRepository.swift
> +        try await uploadDescriptionFile(client: client, folderPath: "/\(folderName)", description: description)
https://github.com/Horizontal-org/Tella-iOS/pull/189#discussion_r1793812638

2024-10-23 12:07 UTC, merged