disable shared drive button if is empty
Horizontal-org/Tella-iOS pull request #193
Opened 2024-09-23 19:23 UTC by ValbuenaG

For more information on contributing to Tella source code, see the [Contributor Guidelines](contributing/contributor_guide.md).

## Type of change

**Description:**

**Select the type of change(s) made in this pull request:**
- [ ] Bug fix *(Fixes an issue)*
- [ ] New feature *(Adds functionality)*
- [ ] Documentation *(Fix to documentation)*

----------------------------------------------------------------------------------------

Fixes #issue-number

## Proposed changes 

* Hide shared drives button if user does not have any drives
* change documentation url
*

2024-10-01 16:49 UTC, dhekra-rouatbi requested changes

2024-10-01 16:49 UTC, dhekra-rouatbi commented on Tella/Scenes/Settings/Views/Servers/GDrive/SelectDriveConnectionView.swift
> +    private var isValidSharedDriveButton: Bool {
maybe it's better to move this variable to `gDriveServerViewModel` ?

2024-10-02 11:16 UTC, Rimktarii requested changes

2024-10-02 11:16 UTC, Rimktarii commented on Tella/Scenes/Settings/Views/Servers/GDrive/SelectDriveConnectionView.swift
> +                isValid: .constant(isValidSharedDriveButton),
I think we should remove .constant

2024-10-03 18:39 UTC, merged