Description field should not be mandatory in ANY of the server connec…
Horizontal-org/Tella-iOS pull request #198
Opened 2024-09-25 20:49 UTC by dhekra-rouatbi

**Select the type of change(s) made in this pull request:**
- [X] Bug fix *(Fixes an issue)*
- [ ] New feature *(Adds functionality)*
- [ ] Documentation *(Fix to documentation)*

----------------------------------------------------------------------------------------

Fixes #issue-number

T-iOS-500

2024-09-27 18:37 UTC, ValbuenaG commented
I'm not sure about the task specs. Should it be mandatory for the submission?

2024-10-02 10:16 UTC, Rimktarii requested changes

2024-10-02 10:16 UTC, Rimktarii commented on Tella/Scenes/Nextcloud/ViewModels/NextcloudDraftViewModel.swift
>      }
Maybe we can create a function in `DraftMainViewModel` and then call it in the subclasses : 
Here an example : 
create this method inside `DraftMainViewModel` 
   ```
 func validateTitleAndDescription() {
        self.isValidTitle =  self.title.textValidator()
        self.isValidDescription = self.description.textValidator()
        self.objectWillChange.send()
    }

```
and call it here :


` self.validateTitleAndDescription()
`

The same for the other connections

2024-10-02 10:16 UTC, Rimktarii commented on Tella/Scenes/Nextcloud/ViewModels/NextcloudDraftViewModel.swift
> +
Maybe we can remove this because it is called  twice

2024-10-02 18:41 UTC, Rimktarii requested changes

2024-10-02 18:41 UTC, Rimktarii commented on Tella/Scenes/CommonConnectionReport/ViewModels/DraftMainViewModel.swift
> +        self.isValidDescription = self.description.textValidator()
I think we missed this here :  `self.objectWillChange.send()`

2024-10-07 14:27 UTC, merged